name: etcd

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - feature-etcdclient

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      etcd:
        image: k8s.gcr.io/etcd:3.5.0-0
        ports:
          - 2379:2379
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      #- name: Test
      #  run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

      - uses: codecov/codecov-action@v2