name: etcd

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - feature-etcdclient

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: addnab/docker-run-action@v3
        with:
          username: zfkhhh
          password: zfk857213
          registry: quay.io
          image: coreos/etcd:latest
          options: -p 2379:2379