name: etcd

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - feature-etcdclient

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run the etcd
        run: |
          docker version
          docker login -u zfkhhh -p zfk857213
          docker pull quay.io/coreos/etcd:latest
          docker network create etcd --driver bridge
          docker run -d --name etcd-server \
              --network etcd \
              --publish 2379:2379 \
              --publish 2380:2380 \
              --env ALLOW_NONE_AUTHENTICATION=yes \
              --env ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379 \
              quay.io/coreos/etcd:latest
          echo `curl http://127.0.0.1:2379/version`