name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      etcd:
        # Docker Hub image
        image: bitnami/etcd:3.5
        env:
          ETCD_ADVERTISE_CLIENT_URLS: http://127.0.0.1:12379
          ALLOW_NONE_AUTHENTICATION: yes
        ports:
          - 12379:2379
          - 12380:2380
      steps:
        - uses: actions/checkout@v3

        - name: Run the etcd
          run: |
            curl -H "Expect:" -v http://localhost:12379/health

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

      - uses: codecov/codecov-action@v2
